from collections import deque

a = deque([1,2,3])
print(a)
a.appendleft('A')
print(a)
a.extendleft([10,20,30])
print(a)
a.extend([100,200,300])
print(a)
a.append(['q','w','e'])
print(a)
print("***")
print(a.remove(10))
print(a)
print(a.pop())
print(a)
a.popleft()
print(a)
a.__delitem__(3)
print(a)
print("-------")
a = list(a)
print(a)